spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  application:
    name: cerebra-api
  cache:
    type: caffeine
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=cerebraDB;encrypt=false
    username: SA
    password: Mvr#2025
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1740000
      pool-name: CerebraDBConnection
      leak-detection-threshold: 5000
      validation-timeout: 5000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
  output:
    ansi:
      enabled: always
  profiles:
    active:
      - cerebra
server:
  servlet:
    context-path: /cerebra
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: file-processing-service
